name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install latest nightly rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
    - name: Build luau-rs
      uses: actions-rs/cargo@v1
      with:
        toolchain: nightly
        command: build
    - name: Run tests in luau-rs
      uses: actions-rs/cargo@v1
      with:
        command: test
        toolchain: nightly
        args: --verbose
